# -*- coding: utf-8 -*-
"""Day1 Assignment .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nMsczoO6cwnhllKqcloK3icfjAVsTee-

Ques1:
"""

X = int(input('Enter number1:'))
Y = int(input('Enter number2:'))
print(X**Y)

"""Ques2:

"""

list =[10,12,3,5,8,9]
vals= [i for i in list if i % 3 == 0]
print(vals)